// Generated by CoffeeScript 1.4.0

/*
    xs_control_tests.coffee

    Copyright (C) 2013, Connected Sets

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


(function() {
  var Control, Ordered_Set, Set, Table, XS, chai, checkbox, checkbox_group, checkbox_group_source, checkbox_source, options, organizer;

  XS = typeof require !== "undefined" && require !== null ? (require('../lib/xs.js')).XS : this.XS;

  if (typeof require !== "undefined" && require !== null) {
    require('../lib/code.js');
    require('../lib/fork.js');
    require('../lib/filter.js');
    require('../lib/ordered_set.js');
    require('../lib/aggregator.js');
    require('../lib/table.js');
    require('../lib/control.js');
  }

  if (typeof require !== "undefined" && require !== null) {
    chai = require('chai');
  }

  if (chai != null) {
    chai.should();
  }

  Set = XS.Set;

  Table = XS.Table;

  Ordered_Set = XS.Ordered_Set;

  Control = XS.Control;

  organizer = [
    {
      id: "id"
    }
  ];

  options = {
    label: "Charts"
  };

  checkbox_source = new Ordered_Set([], organizer, {
    name: "Checkbox Source"
  });

  checkbox = checkbox_source.checkbox(document.getElementById("checkbox_control"), organizer, options);

  checkbox_group_source = new Set([], {
    name: "Checkbox Group Source"
  });

  checkbox_group = checkbox_group_source.checkbox_group(document.getElementById("checkbox_group_control"), organizer, {});

  describe('Checkbox():', function() {
    it('checkbox should be empty', function() {
      return checkbox.get().should.be.empty;
    });
    describe('add():', function() {
      it('after checkbox_source.add( object ), checkbox_source should be equal to [ { id: true, label: "Label True" } ]', function() {
        checkbox_source.add([
          {
            id: true,
            label: "Label True"
          }
        ]);
        return checkbox_source.get().should.be.eql([
          {
            id: true,
            label: "Label True"
          }
        ]);
      });
      it('after checkbox_source.add( object ), checkbox should be equal to [ { id: true, label: "Label True" } ]', function() {
        return checkbox.get().should.be.eql([
          {
            id: true,
            label: "Label True"
          }
        ]);
      });
      it('checkbox.value should be equal to { id: true, label: "Label True" }', function() {
        return checkbox.value.should.be.eql({
          id: true,
          label: "Label True"
        });
      });
      it('after checkbox_source.add( object ), checkbox should be equal to [ { id: false, label: "Label False" }, { id: true, label: "Label True" } ]', function() {
        checkbox_source.add([
          {
            id: false,
            label: "Label False"
          }
        ]);
        return checkbox.get().should.be.eql([
          {
            id: false,
            label: "Label False"
          }, {
            id: true,
            label: "Label True"
          }
        ]);
      });
      return it('checkbox.value should be equal to { id: true, label: "Label True" }', function() {
        return checkbox.value.should.be.eql({
          id: true,
          label: "Label True"
        });
      });
    });
    describe('update():', function() {
      return it('after checkbox_source.update( objects ) checkbox should be equal to [ { id: false, label: "Charts" }, { id: true, label: "Charts" } ]', function() {
        checkbox_source.update([
          [
            {
              id: true,
              label: "Label True"
            }, {
              id: true,
              label: "Charts"
            }
          ], [
            {
              id: false,
              label: "Label False"
            }, {
              id: false,
              label: "Charts"
            }
          ]
        ]);
        return checkbox.get().should.be.eql([
          {
            id: false,
            label: "Charts"
          }, {
            id: true,
            label: "Charts"
          }
        ]);
      });
    });
    return describe('remove():', function() {
      it('after checkbox_source.remove( object ), checkbox should be equal to [ { id: true, label: "Charts" } ]', function() {
        checkbox_source.remove([
          {
            id: false,
            label: "Charts"
          }
        ]);
        return checkbox.get().should.be.eql([
          {
            id: true,
            label: "Charts"
          }
        ]);
      });
      it('checkbox.value should be equal to { id: true, label: "Charts" }', function() {
        return checkbox.value.should.be.eql({
          id: true,
          label: "Charts"
        });
      });
      return it('after checkbox_source.remove( object ), checkbox should be empty', function() {
        checkbox_source.remove([
          {
            id: true,
            label: "Charts"
          }
        ]);
        return checkbox.get().should.be.empty;
      });
    });
  });

  describe('Checkbox_Group():', function() {
    it('checkbox_group should be empty', function() {
      return checkbox_group.get().should.be.empty;
    });
    it('after checkbox_group_source.add( objects ), checkbox_group should be equal to result', function() {
      checkbox_group_source.add([
        {
          id: 1,
          label: "Photography",
          checked: true
        }, {
          id: 2,
          label: "Fishing"
        }, {
          id: 3,
          label: "Playing Computer Games"
        }, {
          id: 4,
          label: "Traveling",
          checked: true
        }, {
          id: 5,
          label: "Cooking"
        }, {
          id: 6,
          label: "Stamp / Coin Collection",
          checked: true
        }
      ]);
      return checkbox_group.get().should.be.eql([
        {
          id: 1,
          label: "Photography",
          checked: true
        }, {
          id: 4,
          label: "Traveling",
          checked: true
        }, {
          id: 6,
          label: "Stamp / Coin Collection",
          checked: true
        }
      ]);
    });
    it('after checkbox_group_source.remove( object ), checkbox_group should be equal to result', function() {
      checkbox_group_source.remove([
        {
          id: 3,
          label: "Playing Computer Games"
        }, {
          id: 4,
          label: "Traveling",
          checked: true
        }
      ]);
      return checkbox_group.get().should.be.eql([
        {
          id: 1,
          label: "Photography",
          checked: true
        }, {
          id: 6,
          label: "Stamp / Coin Collection",
          checked: true
        }
      ]);
    });
    it('after checkbox_group_source.add( object ), checkbox_group should be equal to result', function() {
      checkbox_group_source.add([
        {
          id: 7,
          label: "Pottery",
          checked: true
        }, {
          id: 8,
          label: "Gardening"
        }
      ]);
      return checkbox_group.get().should.be.eql([
        {
          id: 1,
          label: "Photography",
          checked: true
        }, {
          id: 6,
          label: "Stamp / Coin Collection",
          checked: true
        }, {
          id: 7,
          label: "Pottery",
          checked: true
        }
      ]);
    });
    return it('after checkbox_group_source.update( objects ), checkbox_group should be equal to result', function() {
      checkbox_group_source.update([
        [
          {
            id: 3,
            label: "Playing Computer Games"
          }, {
            id: 3,
            label: "Playing Video Games"
          }
        ], [
          {
            id: 7,
            label: "Pottery",
            checked: true
          }, {
            id: 7,
            label: "Pottery",
            checked: false
          }
        ], [
          {
            id: 8,
            label: "Gardening"
          }, {
            id: 8,
            label: "Gardening and Plants",
            checked: true
          }
        ]
      ]);
      return checkbox_group.get().should.be.eql([
        {
          id: 1,
          label: "Photography",
          checked: true
        }, {
          id: 6,
          label: "Stamp / Coin Collection",
          checked: true
        }, {
          id: 8,
          label: "Gardening and Plants",
          checked: true
        }
      ]);
    });
  });

}).call(this);
