// Generated by CoffeeScript 1.4.0
(function() {
  var XS, chai, clone;

  clone = function(o) {
    var p, r;
    if (typeof o !== 'object' || o === null) {
      return o;
    }
    r = o instanceof Array ? [] : {};
    for (p in o) {
      if (o.hasOwnProperty(p)) {
        r[p] = clone(o[p]);
      }
    }
    return r;
  };

  describe('clone():', function() {
    var bar, foo;
    foo = {
      id: 10,
      array: [
        1, 2, "a", "b", 3, {
          x: 10,
          y: void 0,
          z: null
        }
      ],
      obj: {
        coordinate: 1,
        label: "Coordinate",
        values: [24, null, void 0]
      }
    };
    bar = clone(foo);
    return it('foo should be deep equal to bar', function() {
      return bar.should.be.eql(foo);
    });
  });

  XS = typeof require !== "undefined" && require !== null ? (require('../src/xs.js')).XS : this.XS;

  if (typeof require !== "undefined" && require !== null) {
    require('../src/code.js');
    require('../src/connection.js');
    require('../src/filter.js');
  }

  if (typeof require !== "undefined" && require !== null) {
    chai = require('chai');
  }

  if (chai != null) {
    chai.should();
  }

  describe('XS test suite:', function() {
    it('XS should be defined:', function() {
      return XS.should.exist;
    });
    describe('XS.extend():', function() {
      var extend, o1, o2, o3, _o2, _o3;
      extend = XS.extend;
      it('extend() should be a function', function() {
        return extend.should.be.a('function');
      });
      o1 = {
        id: 1,
        name: 'khalifa'
      };
      o2 = {
        email: 'knassik@gmail.com'
      };
      _o2 = clone(o2);
      o3 = {
        country: 'Morocco',
        name: 'khalifa nassik',
        email: 'khalifan@gmail.com'
      };
      _o3 = clone(o3);
      it('extend( object ) should be equal to object', function() {
        var result;
        result = extend(o1);
        return result.should.be.eql(o1);
      });
      it('extend( object1, object2 ) should be equal to object', function() {
        var result;
        result = extend(o1, o2);
        return result.should.be.eql({
          id: 1,
          name: 'khalifa',
          email: 'knassik@gmail.com'
        });
      });
      it('o2 should be deep equal to _o2', function() {
        return o2.should.be.eql(_o2);
      });
      it('extend( object1, object2, object3 ) should be equal to object', function() {
        var result;
        result = extend(o1, o2, o3);
        return result.should.be.eql({
          id: 1,
          name: 'khalifa nassik',
          email: 'khalifan@gmail.com',
          country: 'Morocco'
        });
      });
      it('o2 should be deep equal to _o2', function() {
        return o2.should.be.eql(_o2);
      });
      return it('o3 should be deep equal to _o3', function() {
        return o3.should.be.eql(_o3);
      });
    });
    describe('XS.subclass():', function() {
      var Animal, Snake, a, s, subclass;
      subclass = XS.subclass;
      it('subclass() should be a function', function() {
        return subclass.should.be.a('function');
      });
      Animal = function(name) {
        return this.name = name;
      };
      a = new Animal('Sam');
      it('a should be an instance of Animal', function() {
        return a.should.be.an["instanceof"](Animal);
      });
      Snake = function(name) {};
      subclass(Animal, Snake);
      s = new Snake("Barry the Snake");
      it('s should be an instance of Snake', function() {
        return s.should.be.an["instanceof"](Snake);
      });
      it('s should be an instance of Animal', function() {
        return s.should.be.an["instanceof"](Animal);
      });
      return it('a should not be an instance of Snake', function() {
        return a.should.not.be.an["instanceof"](Snake);
      });
    });
    describe('XS.Code():', function() {
      var code, i, test;
      code = new XS.Code('Code Test')._function(null, 'f', []).add('var i')._for('i = -1', ' ++i < 10').end().add('return i').end().get();
      eval(code);
      i = f();
      it('f should be a function', function() {
        return f.should.be.a('function');
      });
      it('i should be equal to 10', function() {
        return i.should.be.eql(10);
      });
      test = 'a[ ++i ] === n';
      code = new XS.Code('Test unfolded while')._function('g', null, ['n'])._var(['a = [ 34, 65, 98, 8, 52, 10, 21, 13, 1, 90, 14 ]', 'l = a.length', 'i = -1']).unrolled_while('if ( ' + test, '|| ' + test, ') return i').add('return -1').end('').get();
      eval(code);
      it('the index of 34 should be 0', function() {
        return g(34).should.be.eql(0);
      });
      it('the index of 52 should be 4', function() {
        return g(52).should.be.eql(4);
      });
      it('the index of 90 should be 9', function() {
        return g(90).should.be.eql(9);
      });
      return it('the index of 1 should be 8', function() {
        return g(1).should.be.eql(8);
      });
    });
    return describe('XS.Set():', function() {
      var Set, cars, cities, employee, set;
      Set = XS.Set;
      set = new Set([]);
      it('set should be a Set', function() {
        return set.should.be.an["instanceof"](Set);
      });
      cities = new Set([
        {
          id: 1,
          name: "Marrakech",
          country: "Morocco"
        }, {
          id: 2,
          name: "Mountain View",
          country: "USA",
          state: "California"
        }, {
          id: 3,
          name: "Paris",
          country: "France"
        }
      ]);
      cars = new Set([
        {
          id: 1,
          brand: "Mercedes",
          model: "C Class"
        }, {
          id: 2,
          brand: "Mercedes",
          model: "S Class"
        }, {
          id: 3,
          brand: "BMW",
          model: "M Serie"
        }
      ], {
        key: ["id", "model"]
      });
      employee = new XS.Set([
        {
          id: 1,
          name: "Stephen C. Cox",
          salary: "$3000",
          customer_id: "222",
          order_id: "1222"
        }, {
          id: 2,
          name: "Josephin Tan",
          salary: "$1500",
          customer_id: "223",
          order_id: "1223"
        }, {
          id: 3,
          name: "Joyce Ming",
          salary: "$2000",
          customer_id: "224",
          order_id: "1224"
        }, {
          id: 4,
          name: "James A. Pentel",
          salary: "$1750",
          customer_id: "225",
          order_id: "1225"
        }, {
          id: 5,
          name: "Alex Frog",
          salary: "$3000",
          customer_id: "226",
          order_id: "1226"
        }, {
          id: 6,
          name: "Tim Hancook",
          salary: "$1500",
          customer_id: "227",
          order_id: "1227"
        }
      ]);
      describe('get():', function() {
        it('set.get() should be empty', function() {
          return set.get().should.be.eql([]);
        });
        return it('cars.get() should be equal to result', function() {
          var result;
          result = [
            {
              id: 1,
              brand: "Mercedes",
              model: "C Class"
            }, {
              id: 2,
              brand: "Mercedes",
              model: "S Class"
            }, {
              id: 3,
              brand: "BMW",
              model: "M Serie"
            }
          ];
          return cars.get().should.be.eql(result);
        });
      });
      describe('add():', function() {
        var result;
        cities.add([
          {
            id: 4,
            name: "Berlin",
            country: "Germany"
          }
        ]);
        it('cities.add( object ) should be a Set', function() {
          return cities.should.be.an["instanceof"](Set);
        });
        result = new Set([
          {
            id: 1,
            name: "Marrakech",
            country: "Morocco"
          }, {
            id: 2,
            name: "Mountain View",
            country: "USA",
            state: "California"
          }, {
            id: 3,
            name: "Paris",
            country: "France"
          }, {
            id: 4,
            name: "Berlin",
            country: "Germany"
          }
        ]);
        return it('cities.add( object ) should be equal to result', function() {
          return cities.get().should.be.eql(result.get());
        });
      });
      describe('index_of():', function() {
        it('set.index_of( { id: 2 } ) should be -1: empty set', function() {
          return set.index_of({
            id: 2
          }).should.be.eql(-1);
        });
        it('cities.index_of( { id: 2 } ) should be 1', function() {
          return cities.index_of({
            id: 2
          }).should.be.eql(1);
        });
        it('cars.index_of( { id: 2, model: "S Class" } ) should be 1', function() {
          return cars.index_of({
            id: 2,
            model: "S Class"
          }).should.be.eql(1);
        });
        return it('cars.index_of( { id: 3, model: "S Class" } ) should be -1: not found', function() {
          return cars.index_of({
            id: 3,
            model: "S Class"
          }).should.be.eql(-1);
        });
      });
      describe('remove():', function() {
        it('set.remove( [ { id: 1 } ] ) should be equal to set: empty set', function() {
          return set.remove([
            {
              id: 1
            }
          ]).get().should.be.eql(set.get());
        });
        it('employee.remove( [ { id: 15 } ] ) should be equal to employee: record with id 15 doesn\'t exist', function() {
          employee.remove([
            {
              id: 15
            }
          ]);
          return employee.get().should.be.equal(employee.get());
        });
        it('employee.remove( [ { id: 1 } ] ) should be equal to result: first record', function() {
          var result;
          result = new Set([
            {
              id: 2,
              name: "Josephin Tan",
              salary: "$1500",
              customer_id: "223",
              order_id: "1223"
            }, {
              id: 3,
              name: "Joyce Ming",
              salary: "$2000",
              customer_id: "224",
              order_id: "1224"
            }, {
              id: 4,
              name: "James A. Pentel",
              salary: "$1750",
              customer_id: "225",
              order_id: "1225"
            }, {
              id: 5,
              name: "Alex Frog",
              salary: "$3000",
              customer_id: "226",
              order_id: "1226"
            }, {
              id: 6,
              name: "Tim Hancook",
              salary: "$1500",
              customer_id: "227",
              order_id: "1227"
            }
          ]);
          employee.remove([
            {
              id: 1
            }
          ]);
          return employee.get().should.be.eql(result.get());
        });
        it('employee.remove( [ { id: 5 } ] ) should be equal to result: record in the middle', function() {
          var result;
          result = new Set([
            {
              id: 2,
              name: "Josephin Tan",
              salary: "$1500",
              customer_id: "223",
              order_id: "1223"
            }, {
              id: 3,
              name: "Joyce Ming",
              salary: "$2000",
              customer_id: "224",
              order_id: "1224"
            }, {
              id: 4,
              name: "James A. Pentel",
              salary: "$1750",
              customer_id: "225",
              order_id: "1225"
            }, {
              id: 6,
              name: "Tim Hancook",
              salary: "$1500",
              customer_id: "227",
              order_id: "1227"
            }
          ]);
          employee.remove([
            {
              id: 5
            }
          ]);
          return employee.get().should.be.eql(result.get());
        });
        return it('employee.remove( [ { id: 6 } ] ) should be equal to result: last record', function() {
          var result;
          result = new Set([
            {
              id: 2,
              name: "Josephin Tan",
              salary: "$1500",
              customer_id: "223",
              order_id: "1223"
            }, {
              id: 3,
              name: "Joyce Ming",
              salary: "$2000",
              customer_id: "224",
              order_id: "1224"
            }, {
              id: 4,
              name: "James A. Pentel",
              salary: "$1750",
              customer_id: "225",
              order_id: "1225"
            }
          ]);
          employee.remove([
            {
              id: 6
            }
          ]);
          return employee.get().should.be.eql(result.get());
        });
      });
      describe('update():', function() {
        it('set.update( [ [ { id: 1 } ] ] ) should be equal to set: empty set', function() {
          return set.update([
            [
              {
                id: 1
              }
            ]
          ]).get().should.be.eql(set.get());
        });
        it('employee.update( [ [ { id: 15, name: "Khalifa P Nassik", Salary: "$1500" } ] ] ) should be equal to employee: record with id 15 doesn\'t exist', function() {
          employee.update([
            [
              {
                id: 15,
                name: "Khalifa P Nassik",
                Salary: "$1500"
              }
            ]
          ]);
          return employee.get().should.be.equal(employee.get());
        });
        return it('employee.update( [ [ { id: 3 }, { id: 3, name: "Khalifa P Nassik", Salary: "$1500", customer_id: "224", order_id: "1224" ] ] } ) should be equal to result', function() {
          var result;
          result = new Set([
            {
              id: 2,
              name: "Josephin Tan",
              salary: "$1500",
              customer_id: "223",
              order_id: "1223"
            }, {
              id: 3,
              name: "Khalifa P Nassik",
              Salary: "$1500",
              customer_id: "224",
              order_id: "1224"
            }, {
              id: 4,
              name: "James A. Pentel",
              salary: "$1750",
              customer_id: "225",
              order_id: "1225"
            }
          ]);
          employee.update([
            [
              {
                id: 3
              }, {
                id: 3,
                name: "Khalifa P Nassik",
                Salary: "$1500",
                customer_id: "224",
                order_id: "1224"
              }
            ]
          ]);
          return employee.get().should.be.eql(result.get());
        });
      });
      describe('filter():', function() {
        var cities_in_usa, is_in_usa;
        is_in_usa = function(o) {
          return o.country === 'USA';
        };
        cities_in_usa = cities.filter(is_in_usa);
        it('cities_in_usa should be a Set', function() {
          return cities_in_usa.should.be.an["instanceof"](Set);
        });
        it('cities_in_usa should only contain cities in USA', function() {
          return cities_in_usa.get().should.be.eql([
            {
              id: 2,
              name: "Mountain View",
              country: "USA",
              state: "California"
            }
          ]);
        });
        describe('add():', function() {
          it('cities_in_usa should be equal to result: cities.add( [ { id: 5, name: "New York", country: "USA", state: "New York" } ] )', function() {
            var result;
            result = [
              {
                id: 2,
                name: "Mountain View",
                country: "USA",
                state: "California"
              }, {
                id: 5,
                name: "New York",
                country: "USA",
                state: "New York"
              }
            ];
            cities.add([
              {
                id: 5,
                name: "New York",
                country: "USA",
                state: "New York"
              }
            ]);
            return cities_in_usa.get().should.be.eql(result);
          });
          return it('cities_in_usa should be equal to result: cities.add( [ { id: 6, name: "Casablanca", country: "Morocco" }, { id: 7, name: "Housten", country: "USA", state: "Texas" } ] )', function() {
            var result;
            result = [
              {
                id: 2,
                name: "Mountain View",
                country: "USA",
                state: "California"
              }, {
                id: 5,
                name: "New York",
                country: "USA",
                state: "New York"
              }, {
                id: 7,
                name: "Housten",
                country: "USA",
                state: "Texas"
              }
            ];
            cities.add([
              {
                id: 6,
                name: "Casablanca",
                country: "Morocco"
              }, {
                id: 7,
                name: 'Housten',
                country: 'USA',
                state: 'Texas'
              }
            ]);
            return cities_in_usa.get().should.be.eql(result);
          });
        });
        describe('update', function() {
          it('cities_in_usa should be equal to result: cities.update( [ [ { id: 5 }, { id: 5, name: "NY", country: "USA", state: "NY" } ] ] )', function() {
            var result;
            result = [
              {
                id: 2,
                name: "Mountain View",
                country: "USA",
                state: "California"
              }, {
                id: 5,
                name: "NY",
                country: "USA",
                state: "NY"
              }, {
                id: 7,
                name: "Housten",
                country: "USA",
                state: "Texas"
              }
            ];
            cities.update([
              [
                {
                  id: 5,
                  name: "New York",
                  country: "USA",
                  state: "New York"
                }, {
                  id: 5,
                  name: "NY",
                  country: "USA",
                  state: "NY"
                }
              ]
            ]);
            return cities_in_usa.get().should.be.eql(result);
          });
          it('cities_in_usa should be equal to result: cities.update( [ [ { id: 7 }, { id: 7, name: "Venice", country: "Italy" } ] ] )', function() {
            var result;
            result = [
              {
                id: 2,
                name: "Mountain View",
                country: "USA",
                state: "California"
              }, {
                id: 5,
                name: "NY",
                country: "USA",
                state: "NY"
              }
            ];
            cities.update([
              [
                {
                  id: 7,
                  name: "Housten",
                  country: "USA",
                  state: "Texas"
                }, {
                  id: 7,
                  name: "Venice",
                  country: "Italy"
                }
              ]
            ]);
            return cities_in_usa.get().should.be.eql(result);
          });
          it('cities_in_usa should be equal to result: cities.update( [ [ { id: 3 }, { id: 8, name: "Detroit", country: "USA", state: "Michigan" } ] ] )', function() {
            var result;
            result = [
              {
                id: 2,
                name: "Mountain View",
                country: "USA",
                state: "California"
              }, {
                id: 5,
                name: "NY",
                country: "USA",
                state: "NY"
              }, {
                id: 8,
                name: "Detroit",
                country: "USA",
                state: "Michigan"
              }
            ];
            cities.update([
              [
                {
                  id: 3,
                  name: "Paris",
                  country: "France"
                }, {
                  id: 8,
                  name: "Detroit",
                  country: "USA",
                  state: "Michigan"
                }
              ]
            ]);
            return cities_in_usa.get().should.be.eql(result);
          });
          return it('cities_in_usa should be equal to result: cities.update( [ [ { id: 3 }, { id: 9, name: "Madrid", country: "Spain" } ] ] )', function() {
            var result;
            result = [
              {
                id: 2,
                name: "Mountain View",
                country: "USA",
                state: "California"
              }, {
                id: 5,
                name: "NY",
                country: "USA",
                state: "NY"
              }, {
                id: 8,
                name: "Detroit",
                country: "USA",
                state: "Michigan"
              }
            ];
            cities.update([
              [
                {
                  id: 3,
                  name: "Paris",
                  country: "France"
                }, {
                  id: 9,
                  name: "Madrid",
                  country: "Spain"
                }
              ]
            ]);
            return cities_in_usa.get().should.be.eql(result);
          });
        });
        return describe('remove()', function() {
          it('cities_in_usa should be equal to result: cities.remove( [ { id: 2, name: "Mountain View", country: "USA", state: "California" } ] )', function() {
            var result;
            result = [
              {
                id: 5,
                name: "NY",
                country: "USA",
                state: "NY"
              }, {
                id: 8,
                name: "Detroit",
                country: "USA",
                state: "Michigan"
              }
            ];
            cities.remove([
              {
                id: 2,
                name: "Mountain View",
                country: "USA",
                state: "California"
              }
            ]);
            return cities_in_usa.get().should.be.eql(result);
          });
          return it('cities_in_usa should be equal to result: cities.remove( [ { id: 7, name: "Venice", country: "Italy" } ] )', function() {
            var result;
            result = [
              {
                id: 5,
                name: "NY",
                country: "USA",
                state: "NY"
              }, {
                id: 8,
                name: "Detroit",
                country: "USA",
                state: "Michigan"
              }
            ];
            cities.remove([
              {
                id: 7,
                name: "Venice",
                country: "Italy"
              }
            ]);
            return cities_in_usa.get().should.be.eql(result);
          });
        });
      });
      describe('notify():', function() {
        it('add(): employee.notify( transaction ) should be equal to result', function() {
          var result, transaction;
          transaction = [
            {
              action: "add",
              objects: [
                {
                  id: 7,
                  name: "John Morrison",
                  salary: "$3000",
                  customer_id: "228",
                  order_id: "1228"
                }, {
                  id: 8,
                  name: "Thomas Buch",
                  salary: "$2500",
                  customer_id: "229",
                  order_id: "1229"
                }
              ]
            }
          ];
          result = [
            {
              id: 2,
              name: "Josephin Tan",
              salary: "$1500",
              customer_id: "223",
              order_id: "1223"
            }, {
              id: 3,
              name: "Khalifa P Nassik",
              Salary: "$1500",
              customer_id: "224",
              order_id: "1224"
            }, {
              id: 4,
              name: "James A. Pentel",
              salary: "$1750",
              customer_id: "225",
              order_id: "1225"
            }, {
              id: 7,
              name: "John Morrison",
              salary: "$3000",
              customer_id: "228",
              order_id: "1228"
            }, {
              id: 8,
              name: "Thomas Buch",
              salary: "$2500",
              customer_id: "229",
              order_id: "1229"
            }
          ];
          employee.notify(transaction);
          return employee.get().should.be.eql(result);
        });
        it('remove(): employee.notify( transaction ) should be equal to result', function() {
          var result, transaction;
          transaction = [
            {
              action: "remove",
              objects: [
                {
                  id: 8
                }
              ]
            }
          ];
          result = [
            {
              id: 2,
              name: "Josephin Tan",
              salary: "$1500",
              customer_id: "223",
              order_id: "1223"
            }, {
              id: 3,
              name: "Khalifa P Nassik",
              Salary: "$1500",
              customer_id: "224",
              order_id: "1224"
            }, {
              id: 4,
              name: "James A. Pentel",
              salary: "$1750",
              customer_id: "225",
              order_id: "1225"
            }, {
              id: 7,
              name: "John Morrison",
              salary: "$3000",
              customer_id: "228",
              order_id: "1228"
            }
          ];
          employee.notify(transaction);
          return employee.get().should.be.eql(result);
        });
        it('update(): employee.notify( transaction ) should be equal to result', function() {
          var result, transaction;
          transaction = [
            {
              action: "update",
              objects: [
                [
                  {
                    id: 7,
                    name: "John Morrison",
                    salary: "$3000",
                    customer_id: "228",
                    order_id: "1228"
                  }, {
                    id: 7,
                    name: "John Morrison",
                    salary: "$3500",
                    customer_id: "228",
                    order_id: "1228"
                  }
                ], [
                  {
                    id: 2,
                    name: "Josephin Tan",
                    salary: "$1500",
                    customer_id: "223",
                    order_id: "1223"
                  }, {
                    id: 2,
                    name: "Josephin Tan",
                    salary: "$2750",
                    customer_id: "223",
                    order_id: "1223"
                  }
                ]
              ]
            }
          ];
          result = [
            {
              id: 2,
              name: "Josephin Tan",
              salary: "$2750",
              customer_id: "223",
              order_id: "1223"
            }, {
              id: 3,
              name: "Khalifa P Nassik",
              Salary: "$1500",
              customer_id: "224",
              order_id: "1224"
            }, {
              id: 4,
              name: "James A. Pentel",
              salary: "$1750",
              customer_id: "225",
              order_id: "1225"
            }, {
              id: 7,
              name: "John Morrison",
              salary: "$3500",
              customer_id: "228",
              order_id: "1228"
            }
          ];
          employee.notify(transaction);
          return employee.get().should.be.eql(result);
        });
        return it('filter(): cities.filter( is_in_morocco ) should be equal to result', function() {
          var cities_in_morocco, is_in_morocco, result, transaction;
          is_in_morocco = function(o) {
            return o.country === "Morocco";
          };
          cities_in_morocco = cities.filter(is_in_morocco);
          transaction = [
            {
              action: "add",
              objects: [
                {
                  id: 9,
                  name: "Moscow",
                  country: "Russia"
                }, {
                  id: 10,
                  name: "Tanger",
                  country: "Morocco"
                }
              ]
            }, {
              action: "update",
              objects: [
                [
                  {
                    id: 6,
                    name: "Casablanca",
                    country: "Morocco"
                  }, {
                    id: 6,
                    name: "Casa",
                    country: "Morocco"
                  }
                ], [
                  {
                    id: 10,
                    name: "Tanger",
                    country: "Morocco"
                  }, {
                    id: 11,
                    name: "Cairo",
                    country: "Egypt"
                  }
                ], [
                  {
                    id: 3,
                    name: "Paris",
                    country: "France"
                  }, {
                    id: 12,
                    name: "Fes",
                    country: "Morocco"
                  }
                ], [
                  {
                    id: 9,
                    name: "Madrid",
                    country: "Spain"
                  }, {
                    id: 13,
                    name: "LA",
                    country: "USA",
                    state: "California"
                  }
                ]
              ]
            }, {
              action: "remove",
              objects: [
                {
                  id: 13,
                  name: "LA",
                  country: "USA",
                  state: "California"
                }, {
                  id: 12,
                  name: "Fes",
                  country: "Morocco"
                }, {
                  id: 11,
                  name: "Cairo",
                  country: "Egypt"
                }
              ]
            }
          ];
          cities.notify(transaction);
          result = [
            {
              id: 1,
              name: "Marrakech",
              country: "Morocco"
            }, {
              id: 6,
              name: "Casa",
              country: "Morocco"
            }
          ];
          return cities_in_morocco.get().should.be.eql(result);
        });
      });
      return describe('order():', function() {
        var books, books_ordered_by_ascending_author, books_ordered_by_descending_author, books_ordered_by_descending_year, books_ordered_by_year, by_ascending_author, by_descending_author, organizer;
        books = new Set([
          {
            id: 1,
            title: "A Tale of Two Cities",
            author: "Charles Dickens",
            year: 1859
          }, {
            id: 2,
            title: "The Lord of the Rings",
            author: "J. R. R. Tolkien",
            year: 1955
          }, {
            id: 3,
            title: "The Da Vinci Code",
            author: "Dan Brown",
            year: 2003
          }, {
            id: 4,
            title: "The Alchemist",
            author: "Paulo Coelho",
            year: 1988
          }, {
            id: 5,
            title: "Angels and Demons",
            author: "Dan Brown",
            year: 2000
          }
        ]);
        organizer = new Set([
          {
            id: "year"
          }
        ]);
        by_ascending_author = function(a, b) {
          if ((a = a.author) === (b = b.author)) {
            return 0;
          }
          if (a === void 0) {
            return -1;
          }
          if (b === void 0) {
            return 1;
          }
          if (a === null) {
            return -1;
          }
          if (b === null) {
            return 1;
          }
          if (a < b) {
            return -1;
          }
          if (a > b) {
            return 1;
          }
          return 0;
        };
        by_descending_author = function(a, b) {
          return by_ascending_author(b, a);
        };
        books_ordered_by_year = books.order(organizer, {
          name: 'books_ordered_by_year'
        });
        books_ordered_by_descending_year = books.order(new Set([
          {
            id: "year",
            descending: true
          }
        ]), {
          name: 'books_ordered_by_descending_year',
          insert_before: true
        });
        books_ordered_by_ascending_author = books.order(by_ascending_author, {
          name: 'books_ordered_by_ascending_author'
        });
        books_ordered_by_descending_author = books.order(by_descending_author, {
          name: 'books_ordered_by_descending_author',
          insert_before: true
        });
        it('books_ordered_by_year should be ordered by ascending year', function() {
          return books_ordered_by_year.get().should.be.eql([
            {
              id: 1,
              title: "A Tale of Two Cities",
              author: "Charles Dickens",
              year: 1859
            }, {
              id: 2,
              title: "The Lord of the Rings",
              author: "J. R. R. Tolkien",
              year: 1955
            }, {
              id: 4,
              title: "The Alchemist",
              author: "Paulo Coelho",
              year: 1988
            }, {
              id: 5,
              title: "Angels and Demons",
              author: "Dan Brown",
              year: 2000
            }, {
              id: 3,
              title: "The Da Vinci Code",
              author: "Dan Brown",
              year: 2003
            }
          ]);
        });
        it('books_ordered_by_descending_year should be ordered by descending year', function() {
          return books_ordered_by_descending_year.get().should.be.eql([
            {
              id: 3,
              title: "The Da Vinci Code",
              author: "Dan Brown",
              year: 2003
            }, {
              id: 5,
              title: "Angels and Demons",
              author: "Dan Brown",
              year: 2000
            }, {
              id: 4,
              title: "The Alchemist",
              author: "Paulo Coelho",
              year: 1988
            }, {
              id: 2,
              title: "The Lord of the Rings",
              author: "J. R. R. Tolkien",
              year: 1955
            }, {
              id: 1,
              title: "A Tale of Two Cities",
              author: "Charles Dickens",
              year: 1859
            }
          ]);
        });
        it('books_ordered_by_ascending_author should be ordered by ascending auhtor: organizer is a function', function() {
          return books_ordered_by_ascending_author.get().should.be.eql([
            {
              id: 1,
              title: "A Tale of Two Cities",
              author: "Charles Dickens",
              year: 1859
            }, {
              id: 3,
              title: "The Da Vinci Code",
              author: "Dan Brown",
              year: 2003
            }, {
              id: 5,
              title: "Angels and Demons",
              author: "Dan Brown",
              year: 2000
            }, {
              id: 2,
              title: "The Lord of the Rings",
              author: "J. R. R. Tolkien",
              year: 1955
            }, {
              id: 4,
              title: "The Alchemist",
              author: "Paulo Coelho",
              year: 1988
            }
          ]);
        });
        it('books_ordered_by_descending_author should be ordered by descending auhtor: organizer is a function', function() {
          return books_ordered_by_descending_author.get().should.be.eql([
            {
              id: 4,
              title: "The Alchemist",
              author: "Paulo Coelho",
              year: 1988
            }, {
              id: 2,
              title: "The Lord of the Rings",
              author: "J. R. R. Tolkien",
              year: 1955
            }, {
              id: 3,
              title: "The Da Vinci Code",
              author: "Dan Brown",
              year: 2003
            }, {
              id: 5,
              title: "Angels and Demons",
              author: "Dan Brown",
              year: 2000
            }, {
              id: 1,
              title: "A Tale of Two Cities",
              author: "Charles Dickens",
              year: 1859
            }
          ]);
        });
        describe('add()', function() {
          it('after books.add( book 6 ), books_ordered_by_year should be ordered by ascending year', function() {
            books.add([
              {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }
            ]);
            return books_ordered_by_year.get().should.be.eql([
              {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }
            ]);
          });
          it('after books.add( book 6 ), books_ordered_by_descending_year should be ordered by descending year', function() {
            return books_ordered_by_descending_year.get().should.be.eql([
              {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }
            ]);
          });
          it('after books.add( book 6 ), books_ordered_by_ascending_author should be ordered by ascending auhtor', function() {
            return books_ordered_by_ascending_author.get().should.be.eql([
              {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }
            ]);
          });
          it('after books.add( book 6 ), books_ordered_by_descending_author should be ordered by descending auhtor', function() {
            return books_ordered_by_descending_author.get().should.be.eql([
              {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }
            ]);
          });
          it('after books.add( books 7, 8, 9, 10 ), books_ordered_by_year should be ordered by ascending year', function() {
            books.add([
              {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }
            ]);
            return books_ordered_by_year.get().should.be.eql([
              {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }
            ]);
          });
          it('after books.add( books 7, 8, 9, 10 ), books_ordered_by_descending_year should be ordered by descending year', function() {
            return books_ordered_by_descending_year.get().should.be.eql([
              {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }
            ]);
          });
          it('after books.add( books 7, 8, 9, 10 ), books_ordered_by_ascending_author should be ordered by ascending auhtor', function() {
            return books_ordered_by_ascending_author.get().should.be.eql([
              {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }
            ]);
          });
          it('after books.add( books 11, 12, 13 ), whose years are already used; books_ordered_by_year should be ordered by ascending year', function() {
            books.add([
              {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }
            ]);
            return books_ordered_by_year.get().should.be.eql([
              {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }
            ]);
          });
          it('after books.add( books 11, 12, 13 ), whose years are already used; books_ordered_by_descending_year should be ordered by descending year', function() {
            return books_ordered_by_descending_year.get().should.be.eql([
              {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }
            ]);
          });
          it('after books.add( books 14, 15, 16 ), the years are undefined or null; books_ordered_by_year should be ordered by ascending year', function() {
            books.add([
              {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }
            ]);
            return books_ordered_by_year.get().should.be.eql([
              {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }
            ]);
          });
          it('after books.add( books 14, 15, 16 ), the years are undefined or null; books_ordered_by_descending_year should be ordered by descending year', function() {
            return books_ordered_by_descending_year.get().should.be.eql([
              {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }
            ]);
          });
          it('update organizer, books_ordered_by_year should be ordered by ascending by title', function() {
            organizer.update([
              [
                {
                  id: "year"
                }, {
                  id: "title"
                }
              ]
            ]);
            return books_ordered_by_year.get().should.be.eql([
              {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }
            ]);
          });
          it('add a second field to organizer, books_ordered_by_year should be ordered by ascending year and title', function() {
            organizer.notify([
              {
                action: "update",
                objects: [
                  [
                    {
                      id: "title"
                    }, {
                      id: "year"
                    }
                  ]
                ]
              }, {
                action: "add",
                objects: [
                  {
                    id: "title"
                  }
                ]
              }
            ]);
            return books_ordered_by_year.get().should.be.eql([
              {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }
            ]);
          });
          it('books_ordered_by_ascending_author should be ordered by ascending auhtor', function() {
            return books_ordered_by_ascending_author.get().should.be.eql([
              {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }
            ]);
          });
          it('books_ordered_by_descending_author should be ordered by descending auhtor', function() {
            return books_ordered_by_descending_author.get().should.be.eql([
              {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }
            ]);
          });
          it('books_ordered_by_ascending_id should be ordered by ascending id: organizer is an objects', function() {
            var books_ordered_by_ascending_id;
            books_ordered_by_ascending_id = books.order([
              {
                id: "id"
              }
            ]);
            return books_ordered_by_ascending_id.get().should.be.eql([
              {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }
            ]);
          });
          return it('books_ordered_by_descending should be ordered by descending id: organizer is an objects', function() {
            var books_ordered_by_ascending_id;
            books_ordered_by_ascending_id = books.order([
              {
                id: "id",
                descending: true
              }
            ]);
            return books_ordered_by_ascending_id.get().should.be.eql([
              {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 2,
                title: "The Lord of the Rings",
                author: "J. R. R. Tolkien",
                year: 1955
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }
            ]);
          });
        });
        describe('update():', function() {
          it('after books.update( object 2 ), books_ordered_by_year should be ordered by ascending year', function() {
            books.update([
              [
                {
                  id: 2,
                  title: "The Lord of the Rings",
                  author: "J. R. R. Tolkien",
                  year: 1955
                }, {
                  id: 2,
                  title: "The Lord of the Rings 1",
                  author: "J. R. R. Tolkien",
                  year: 1954
                }
              ]
            ]);
            return books_ordered_by_year.get().should.be.eql([
              {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 2,
                title: "The Lord of the Rings 1",
                author: "J. R. R. Tolkien",
                year: 1954
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }
            ]);
          });
          it('after books.update( object 2 ), books_ordered_by_descending_year should be ordered by descending year', function() {
            return books_ordered_by_descending_year.get().should.be.eql([
              {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 2008
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 2000
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2000
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 2,
                title: "The Lord of the Rings 1",
                author: "J. R. R. Tolkien",
                year: 1954
              }, {
                id: 8,
                title: "The Hobbit",
                author: "J. R. R. Tolkien",
                year: 1937
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: null
              }, {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: void 0
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl"
              }
            ]);
          });
          it('after books.notify( 4 updates transaction ), books_ordered_by_year should be ordered by ascending year', function() {
            books.notify([
              {
                action: "update",
                objects: [
                  [
                    {
                      id: 8,
                      title: "The Hobbit",
                      author: "J. R. R. Tolkien",
                      year: 1937
                    }, {
                      id: 8,
                      title: "The Hobbit Changed",
                      author: "J. R. R. Tolkien 8",
                      year: 1937
                    }
                  ], [
                    {
                      id: 15,
                      title: "Steps to Christ",
                      author: "Ellen G. White",
                      year: null
                    }, {
                      id: 15,
                      title: "Steps to Christ",
                      author: "Ellen G. White",
                      year: void 0
                    }
                  ], [
                    {
                      id: 16,
                      title: "Charlie and the Chocolate Factory",
                      author: "Roald Dahl"
                    }, {
                      id: 16,
                      title: "Charlie and the Chocolate Factory",
                      author: "Roald Dahl",
                      year: 1970
                    }
                  ], [
                    {
                      id: 14,
                      title: "And Then There Were None",
                      author: "Agatha Christie",
                      year: void 0
                    }, {
                      id: 14,
                      title: "And Then There Were None",
                      author: "Agatha Christie",
                      year: 1927
                    }
                  ], [
                    {
                      id: 2,
                      title: "The Lord of the Rings 1",
                      author: "J. R. R. Tolkien",
                      year: 1954
                    }, {
                      id: 2,
                      title: "The Lord of the Rings 1",
                      author: "J. R. R. Tolkien 2",
                      year: 1954
                    }
                  ], [
                    {
                      id: 11,
                      title: "The Dukan Diet",
                      author: "Pierre Dukan",
                      year: 2000
                    }, {
                      id: 11,
                      title: "The Dukan Diet",
                      author: "Pierre Dukan",
                      year: 1999
                    }
                  ], [
                    {
                      id: 5,
                      title: "Angels and Demons",
                      author: "Dan Brown",
                      year: 2000
                    }, {
                      id: 5,
                      title: "Angels and Demons",
                      author: "Dan Brown",
                      year: 2001
                    }
                  ], [
                    {
                      id: 12,
                      title: "Breaking Dawn",
                      author: "Stephenie Meyer",
                      year: 2008
                    }, {
                      id: 12,
                      title: "Breaking Dawn",
                      author: "Stephenie Meyer",
                      year: 1875
                    }
                  ], [
                    {
                      id: 9,
                      title: "The Hunger Games",
                      author: "Suzanne Collins",
                      year: 2008
                    }, {
                      id: 9,
                      title: "The Hunger Games",
                      author: "Suzanne Collins",
                      year: 1942
                    }
                  ]
                ]
              }
            ]);
            return books_ordered_by_year.get().should.be.eql([
              {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: void 0
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 1875
              }, {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: 1927
              }, {
                id: 8,
                title: "The Hobbit Changed",
                author: "J. R. R. Tolkien 8",
                year: 1937
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 1942
              }, {
                id: 2,
                title: "The Lord of the Rings 1",
                author: "J. R. R. Tolkien 2",
                year: 1954
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl",
                year: 1970
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 1999
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2001
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }
            ]);
          });
          return it('after books.notify( transaction ), books_ordered_by_descending_year should be ordered by descending year', function() {
            return books_ordered_by_descending_year.get().should.be.eql([
              {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2001
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 1999
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl",
                year: 1970
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 2,
                title: "The Lord of the Rings 1",
                author: "J. R. R. Tolkien 2",
                year: 1954
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 1942
              }, {
                id: 8,
                title: "The Hobbit Changed",
                author: "J. R. R. Tolkien 8",
                year: 1937
              }, {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: 1927
              }, {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 1875
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: void 0
              }
            ]);
          });
        });
        return describe('remove():', function() {
          it('after books.remove( objects 12, 13, 15 ), books_ordered_by_ascending_author should be ordered by ascending auhtor', function() {
            books.remove([
              {
                id: 12,
                title: "Breaking Dawn",
                author: "Stephenie Meyer",
                year: 2008
              }, {
                id: 13,
                title: "Lolita",
                author: "Vladimir Nabokov",
                year: 1955
              }, {
                id: 15,
                title: "Steps to Christ",
                author: "Ellen G. White",
                year: void 0
              }
            ]);
            return books_ordered_by_ascending_author.get().should.be.eql([
              {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: 1927
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2001
              }, {
                id: 2,
                title: "The Lord of the Rings 1",
                author: "J. R. R. Tolkien 2",
                year: 1954
              }, {
                id: 8,
                title: "The Hobbit Changed",
                author: "J. R. R. Tolkien 8",
                year: 1937
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 1999
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl",
                year: 1970
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 1942
              }, {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }
            ]);
          });
          return it('after books.remove( objects 12, 13, 15 ), books_ordered_by_descending_author should be ordered by descending auhtor', function() {
            return books_ordered_by_descending_author.get().should.be.eql([
              {
                id: 7,
                title: "The McGuffey Readers",
                author: "William Holmes McGuffey",
                year: 1853
              }, {
                id: 9,
                title: "The Hunger Games",
                author: "Suzanne Collins",
                year: 1942
              }, {
                id: 6,
                title: "The Girl with the Dragon Tattoo",
                author: "Stieg Larsson",
                year: 2005
              }, {
                id: 16,
                title: "Charlie and the Chocolate Factory",
                author: "Roald Dahl",
                year: 1970
              }, {
                id: 11,
                title: "The Dukan Diet",
                author: "Pierre Dukan",
                year: 1999
              }, {
                id: 4,
                title: "The Alchemist",
                author: "Paulo Coelho",
                year: 1988
              }, {
                id: 10,
                title: "Harry Potter and the Prisoner of Azkaban",
                author: "J.K. Rowling",
                year: 1999
              }, {
                id: 8,
                title: "The Hobbit Changed",
                author: "J. R. R. Tolkien 8",
                year: 1937
              }, {
                id: 2,
                title: "The Lord of the Rings 1",
                author: "J. R. R. Tolkien 2",
                year: 1954
              }, {
                id: 3,
                title: "The Da Vinci Code",
                author: "Dan Brown",
                year: 2003
              }, {
                id: 5,
                title: "Angels and Demons",
                author: "Dan Brown",
                year: 2001
              }, {
                id: 1,
                title: "A Tale of Two Cities",
                author: "Charles Dickens",
                year: 1859
              }, {
                id: 14,
                title: "And Then There Were None",
                author: "Agatha Christie",
                year: 1927
              }
            ]);
          });
        });
      });
    });
  });

}).call(this);
