require( "toubkal" )
  .set([ { name:"toubkal/lib/server/toubkal_acorn.js"} ] )
  .require_resolve()
  .watch()
  .acorn()
  .parse_documentation()
  .pick( [ 'path', 'documentation_items' ] )
  .trace()
  .greedy()
;
